// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/og/[slug].tsx";
import * as $4 from "./routes/api/og/index.tsx";
import * as $5 from "./routes/blog/[slug].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/rss/index.ts";
import * as $8 from "./routes/sitemap.xml/index.ts";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/og/[slug].tsx": $3,
    "./routes/api/og/index.tsx": $4,
    "./routes/blog/[slug].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/rss/index.ts": $7,
    "./routes/sitemap.xml/index.ts": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
